apiVersion: v1
kind: Pod
metadata: 
    name: adapter-example
    namespace: default
spec:
    containers:
      - image: redis
        name: redis
      - image: oliver006/redis_exporter
        name: adapter

